select_cols <- function(cols,x){
  cols$cols<-cols$cols[x]
  cols
}

#'@importFrom readr col_character col_date col_double col_integer col_logical cols
shcs_cols <- function(){
    cols(
      #admin
      ID = col_character(),
      REGDATE = col_date(format = ""),
      BORN = col_integer(),
      SEX = col_integer(),
      CENTER1 = col_character(),
      LAST_CENTER = col_character(),
      LAST_FUP_DATE = col_date(format = ""),
      LAST_LAB_DATE = col_date(format = ""),
      LAST_INFO_DATE = col_date(format = ""),
      LAST_FUP_PHYSICIAN = col_character(),
      LAST_FUP_STUDYNURSE = col_character(),
      LAST_FUP_SOURCE = col_integer(),
      FIRST_C_DATE = col_date(format = ""),
      FOPH_REPORT = col_character(),
      FOPH_DATE = col_date(format = ""),
      STOP = col_integer(),
      STOPDATE = col_date(format = ""),
      LIVEDATE = col_date(format = ""),
      EXITDATE = col_date(format = ""),
      EXIT_WHY = col_character(),
      AUTOPSY = col_integer(),
      REGION = col_character(),
      ICD10_MC = col_character(),
      W_CONSENT = col_integer(),
      GENET_CONSENT_DT = col_date(format = ""),
      GENET_REFUSED_DT = col_date(format = ""),
      ALU = col_character(),
      COMMENTS = col_character(),
      #center
      CENTER = col_character(),
      CENTER_NAME = col_character(),
      #clinical
      CLIN_ID = col_character(),
      CLIN_DATE = col_date(format = ""),
      RELIABILITY = col_character(),
      PHYSICIAN = col_character(),
      STUDY_NURSE = col_character(),
      SOURCE = col_integer(),
      CHECK_CHART = col_integer(),
      SEND_DATE = col_date(format = ""),
      CHECK_DATE = col_date(format = ""),
      PAID_DATE = col_date(format = ""),
      #cvrisk
      CARDIODATE = col_date(format = ""),
      SMOKE = col_integer(),
      WEIGHT = col_integer(),
      WAIST = col_integer(),
      HIP = col_integer(),
      SYSTOLIC = col_integer(),
      DIASTOLIC = col_integer(),
      FAT_LOSS = col_integer(),
      FAT_ACCU = col_integer(),
      SMOKE_NB = col_integer(),
      CURRENT_HEIGHT = col_integer(),
      #dborn
      D_BORN = col_integer(),
      #dis
      NEWDATE = col_date(format = ""),
      DISEASE = col_character(),
      DIAGNOSIS = col_character(),
      RELAPSE = col_integer(),
      CANCER = col_character(),
      #drug code
      SUBSTANCE_ID = col_character(),
      INDICATION = col_character(),
      DRUG = col_character(),
      STARTDATE = col_date(format = ""),
      STARTS = col_character(),
      STOPS = col_character(),
      STOP_WHY = col_character(),
      #med drug code
      DRUG_CODE = col_character(),
      DESCRIPTION = col_character(),
      CATEGORY_ID = col_character(),
      #fup
      FUPDATE = col_date(format = ""),
      EARNPRO = col_integer(),
      EARNINS = col_integer(),
      EARNREL = col_integer(),
      EARNSAV = col_integer(),
      EARNOTH = col_integer(),
      EARNOTH_DET = col_character(),
      EARN_PERC = col_integer(),
      EARN_NOI = col_integer(),
      EARNUNE = col_integer(),
      ND_HOSP = col_integer(),
      ND_CEN = col_integer(),
      ND_CEN_NOI = col_integer(),
      ND_OTHER = col_integer(),
      ND_OTHER_NOI = col_integer(),
      ND_WHERE = col_character(),
      ABILITY = col_integer(),
      ABILITY_NOI = col_integer(),
      WORKED = col_integer(),
      WORKED_NOI = col_integer(),
      TAGS = col_character(),
      SETTING = col_integer(),
      CLINIC = col_character(),
      CONSENT2_DATE = col_date(format = ""),
      CONSENT2_SIGN = col_character(),
      FUP_A = col_character(),
      ND_DRUG = col_integer(),
      ND_CVD = col_integer(),
      S_ALONE = col_integer(),
      S_SPOUSE = col_integer(),
      S_WOMAN = col_integer(),
      S_MAN = col_integer(),
      S_FAMILY = col_integer(),
      S_CHILD = col_integer(),
      S_FRIENDS = col_integer(),
      S_INSTITUTION = col_integer(),
      P_STABLE = col_integer(),
      P_STABLE_SEX = col_integer(),
      P_STABLE_CUSE = col_character(),
      P_STABLE_POS = col_character(),
      P_OCCAS = col_integer(),
      P_OCCAS_SEX = col_integer(),
      P_OCCAS_CUSE = col_character(),
      ALCOHOL = col_integer(),
      ALCOHOL_CONS = col_double(),
      FATHERED = col_integer(),
      PSYCHIATRIC = col_integer(),
      PRISON = col_integer(),
      DRUG_PROG = col_integer(),
      TROPICS = col_integer(),
      HERO_IV = col_integer(),
      HERO_IV_F = col_character(),
      COCA_IV = col_integer(),
      COCA_IV_F = col_character(),
      OTHER_IV = col_integer(),
      OTHER_IV_DRUG = col_character(),
      OTHER_IV_F = col_character(),
      HERO_NI = col_integer(),
      HERO_NI_F = col_character(),
      COCA_NI = col_integer(),
      COCA_NI_F = col_character(),
      CANA_NI = col_integer(),
      CANA_NI_F = col_character(),
      OTHER_NI = col_integer(),
      OTHER_NI_DRUG = col_character(),
      OTHER_NI_F = col_character(),
      DEPRESSION = col_integer(),
      ANTIDEPRESS = col_integer(),
      DIAG_PSY = col_integer(),
      DIAG_OTHER_PHYS = col_integer(),
      RECEPTIONDATE = col_date(format = ""),
      LIBIDO = col_integer(),
      ERECTION = col_integer(),
      ACTIVITY_W = col_integer(),
      ACTIVITY_H = col_integer(),
      ACTIVITY_L = col_integer(),
      YF_VACCIN = col_integer(),
      ACTIVITY_HH = col_integer(),
      ALC_FREQ = col_integer(),
      ALC_QUANT = col_integer(),
      ALC_BINGE = col_integer(),
      COG_FREQ = col_integer(),
      COG_CONC = col_integer(),
      COG_SLOW = col_integer(),
      ANAL_CANCER_METH = col_integer(),
      ANAL_CANCER_DATE = col_date(format = ""),
      ANAL_CANCER = col_integer(),
      DEPR_FIRSTEVENT = col_integer(),
      DEPR_DIAGTOOL = col_integer(),
      DIAG_SHCS_PHYS = col_integer(),
      COV_TEST = col_integer(),
      COV_CONTACT = col_integer(),
      COV_VACCINE = col_integer(),
      P_OCCAS_OSEX = col_integer(),
      P_STABLE_OSEX = col_integer(),
      P_OCCAS_NUMBER = col_integer(),
      ND_STD_SCREENING = col_integer(),
      COV_INFECTION = col_integer(),
      COV_INFECTION_DATE = col_date(format = ""),
      #hcv
      HCV_DATE = col_date(format = ""),
      SCCS_PART = col_integer(),
      SCCS_ID = col_character(),
      AGREES = col_integer(),
      #hivsubtype
      SUBTYPE = col_character(),
      #hospital
      IN_DATE = col_date(format = ""),
      OUT_DATE = col_date(format = ""),
      REASON = col_character(),
      #iris
      IRISDATE = col_date(format = ""),
      #lab
      LABDATE = col_date(format = ""),
      CD4DATE = col_date(format = ""),
      LEU = col_integer(),
      HEM = col_double(),
      PLA = col_integer(),
      LYM = col_integer(),
      LYMP = col_double(),
      CD3 = col_integer(),
      CD3P = col_double(),
      CD4 = col_integer(),
      CD4P = col_double(),
      CD8 = col_integer(),
      CD8P = col_double(),
      AGP24_Q = col_character(),
      AGP24 = col_double(),
      ICDP24_Q = col_character(),
      ICDP24 = col_logical(),
      RNA = col_integer(),
      CELLS_TAKEN = col_integer(),
      SERUM_TAKEN = col_integer(),
      PLASMA_TAKEN = col_integer(),
      DNA_TAKEN = col_integer(),
      SAMPLE_DAY = col_date(format = ""),
      SAMPLE_TIME = col_logical(),
      TBC = col_character(),
      TBC_TSR = col_logical(),
      TBC_TESTDATE = col_date(format = ""),
      SYPH_Q = col_character(),
      VDRL_Q = col_character(),
      VDRL = col_integer(),
      SYPH_DATE = col_date(format = ""),
      CMV = col_character(),
      CMV_DATE = col_date(format = ""),
      TOXO = col_character(),
      TOXO_DATE = col_date(format = ""),
      STATUS_REC = col_integer(),
      FUP_LAB = col_integer(),
      LAB_A = col_character(),
      RNA_LIMIT = col_integer(),
      RNA_METHOD = col_integer(),
      AGHBS = col_character(),
      ANTIHBS = col_character(),
      ANTIHBC = col_character(),
      HEB_DATE = col_date(format = ""),
      ANTIHCV = col_character(),
      HEC_DATE = col_date(format = ""),
      HCV_GEN = col_character(),
      HCV_GEN_DATE = col_date(format = ""),
      HCV_RNA = col_integer(),
      HCV_RNA_LIMIT = col_integer(),
      HCV_RNA_UNIT = col_integer(),
      HCV_RNA_DATE = col_date(format = ""),
      HCV_RNA_METH = col_integer(),
      SYPH = col_double(),
      HCV_RNA_QUAL = col_character(),
      AGHBE = col_character(),
      AGHBE_DATE = col_date(format = ""),
      ANTIHBE = col_character(),
      ANTIHBE_DATE = col_date(format = ""),
      ANTIHDV = col_character(),
      ANTIHDV_DATE = col_date(format = ""),
      HBVDNA = col_integer(),
      HBVDNA_QUAL = col_logical(),
      HBVDNA_DATE = col_date(format = ""),
      HBVDNA_METH = col_integer(),
      HBVDNA_LIMIT = col_integer(),
      HBVDNA_UNIT = col_integer(),
      IMPORT = col_character(),
      TBI = col_character(),
      TBI_METHOD = col_integer(),
      TBI_TESTDATE = col_date(format = ""),
      SYPH_METHOD = col_integer(),
      VDRL_METHOD = col_integer(),
      #lab2
      ITEM = col_character(),
      FASTING = col_integer(),
      VALUE = col_double(),
      NORM_SUP = col_double(),
      NORM_INF = col_double(),
      #mborn
      M_BORN = col_integer(),
      #obstet event
      OBSTET_EVENT = col_integer(),
      O_EVENT_DATE = col_date(format = ""),
      #pat
      HEIGHT = col_integer(),
      CONSENT_DATE = col_date(format = ""),
      CONSENT_SIGN = col_character(),
      GEN_INFORM = col_character(),
      ETHNICITY = col_integer(),
      HIV_EARLIER = col_integer(),
      HIV_POSDATE = col_date(format = ""),
      HIV_POSDOCDATE = col_date(format = ""),
      HIV_NEG = col_integer(),
      HIV_NEGDATE = col_date(format = ""),
      HIV_NEGDOC = col_integer(),
      IVD = col_integer(),
      X_PREF = col_integer(),
      RISK = col_integer(),
      EDUCATION = col_integer(),
      PROFESSION = col_integer(),
      FIRST_CENTER = col_integer(),
      FIRST_SOURCE = col_integer(),
      VIRUS_TYPE = col_integer(),
      SUPDATE = col_date(format = ""),
      CV_POS_FAMILY = col_double(),
      CV_DIAB_FAM = col_integer(),
      CV_HYPER = col_integer(),
      CV_HYPERDATE = col_date(format = ""),
      CV_HYPER_TT = col_date(format = ""),
      CV_SMOKED = col_integer(),
      CV_SMOKED_PY = col_integer(),
      PRETREAT = col_integer(),
      INFECT_SOURCE = col_integer(),
      SEX_REGULAR = col_integer(),
      SEX_OCCAS = col_integer(),
      SEX_ANONYM = col_integer(),
      IV_REGULAR = col_integer(),
      IV_OTHER = col_integer(),
      INFECT_TIME = col_integer(),
      SEX1_STARTDATE = col_date(format = ""),
      SEX1_STOPDATE = col_date(format = ""),
      IV1_STARTDATE = col_date(format = ""),
      IV1_STOPDATE = col_date(format = ""),
      SEX2_STARTDATE = col_date(format = ""),
      SEX2_STOPDATE = col_date(format = ""),
      IV2_STARTDATE = col_date(format = ""),
      IV2_STOPDATE = col_date(format = ""),
      OTHER_STARTDATE = col_date(format = ""),
      OTHER_STOPDATE = col_date(format = ""),
      INFECT_PLACE = col_integer(),
      ALC = col_character(),
      GENETIC_SEX = col_integer(),
      INPUTDATE = col_date(format = ""),
      #stop
      STOP_OTH = col_character(),
      EXIT_WHY_OTH = col_character(),
      EXIT_PLACE = col_character(),
      EXIT_PLACE_OTH = col_character(),
      ICD10_SC1 = col_character(),
      ICD10_SC2 = col_character(),
      ICD10_SC3 = col_character(),
      LIFE_INFO = col_integer(),
      CODEFORM = col_integer(),
      #substance in prod
      CONTAINED_SUBSTANCE_ID = col_character(),
      CONTAINING_PRODUCT_ID = col_character(),
      DOSE = col_character(),
      DOSE_VALUE = col_character(),
      DOSE_UNIT = col_character(),
      #substance
      NAME = col_character(),
      TRIAL = col_integer(),
      #tailor
      RISKGROUP = col_character(),
      C_EVENT = col_character(),
      FIRST_B_DATE = col_date(format = ""),
      B_EVENT = col_character(),
      SEROC_DATE = col_date(format = ""),
      SEROC_WINDOW = col_integer(),
      CD4_500_FD = col_date(format = ""),
      CD4_200_FD = col_date(format = ""),
      CD4_100_FD = col_date(format = ""),
      CD4_50_FD = col_date(format = ""),
      CD4_500_FV = col_integer(),
      CD4_200_FV = col_integer(),
      CD4_100_FV = col_integer(),
      CD4_50_FV = col_integer(),
      CD4_AT_REG = col_integer(),
      CD4_FIRST_VAL = col_integer(),
      CD4_FIRST_DATE = col_date(format = ""),
      CD4_AT_AIDS = col_integer(),
      CD4_LAST_VAL = col_integer(),
      CD4_LAST_DATE = col_date(format = ""),
      RNA_FIRST_VAL = col_integer(),
      RNA_FIRST_DATE = col_date(format = ""),
      RNA_LAST_VAL = col_integer(),
      RNA_LAST_DATE = col_date(format = ""),
      RNA_LAST_LIMIT = col_integer(),
      ART_START_DATE = col_date(format = ""),
      ART_START_CD4 = col_integer(),
      HAART_START_DATE = col_date(format = ""),
      CURRENT_ART = col_character(),
      TRI_START_DATE = col_date(format = ""),
      ART_START_RNA = col_integer(),
      #var cancer
      VAR_DESC = col_character(),
      #var clinical
      VAR_DESC = col_character(),
      DIAGNOSIS_TYPE = col_integer(),
      CLIN_GROUP = col_character(),
      DOCU_START = col_date(format = ""),
      DOCU_STOP = col_date(format = ""),
      #disease
      VAR_DESC = col_character(),
      CDC_GROUP = col_character(),
      IRIS = col_integer(),
      #lab 2
      VAR_DESC = col_character(),
      # nation
      NATION = col_character(),
      REGION_ID = col_character(),
      AIDS99 = col_integer(),
      FGM = col_integer()

    )
}
